awslabs/osml-model-runner-test

.github/workflows/documentation.yaml
*Issue #, if available:* N/A
*Description of changes:* Adding a workflow for publishing sphinx documentation.
=> Add workflow for hosting sphinx documentation

src/aws/osml/integ/sm_aircraft/test_sm_aircraft_model.py, src/aws/osml/integ/sm_centerpoint/test_sm_centerpoint_model.py, src/aws/osml/integ/sm_flood/test_sm_flood_model.py, src/aws/osml/utils/integ_utils.py
Fixing the run_model_on_image() function to take in the correct parameters.
*Testing:* 
```
python3 bin/process_image.py --image small --model centerpoint --endpoint_type sm
================================================================================= test session starts =================================================================================
platform darwin -- Python 3.11.4, pytest-7.3.1, pluggy-1.0.0 -- /opt/homebrew/Caskroom/miniconda/base/bin/python3
cachedir: .pytest_cache
rootdir: /Users/drduhe/Github/osml-model-runner-test
configfile: pyproject.toml
plugins: hydra-core-1.3.2
collected 1 item …
```
=> fix: fix run_model_on_image()

bin/get_cost_report.py
Adding a script to grab the cost report for a given hourly time window from an AWS account.
*Testing:* 
Ran script to grab data from my personal dev account:
```
bash-3.2$ python3 bin/get_cost_report.py 2023-10-20T09:00:00Z 2023-10-20T11:00:00Z
╒════╤════════════════════════════════════════╤══════════════╤══════════════════════╕
│    │ Service                                │         Cost │ TimePeriod           │
╞════╪════════════════════════════════════════╪══════════════╪══════════════════════╡
│  0 │ AWS CloudTrail                         │  0           │ 2023-10-20T09:00:00Z │
├────┼────────────────────────────────────────┼──────────────┼──────────────────────┤
│  1 │ AWS Key Management Service             │  0.350811    │ …
```
=> feat: get cost report script

.github/workflows/osml-model-runner-test-publish.yml, .github/workflows/python-publish.yml
- Add workflow to publish this package package to pypi once its merged into main
=> feat: publish python package workflow

src/aws/osml/utils/integ_utils.py, src/data/centerpoint.meta.ntf.geojson, src/data/centerpoint.sicd-interferometric-hh.nitf.geojson
Fixing test data for meta and sicd images
=> fix: fixing test data for meta and sicd images

src/aws/osml/utils/integ_utils.py
Updating the expected region count for the large flood model integration test to reflect changes in default region sizes.
=> fix: updating integ_utils.py

src/data/centerpoint.sicd-capella-chip.ntf.geojson, src/data/centerpoint.sicd-umbra-chip.ntf.geojson
- Update GeoJson results for validating if the test succeeded or not
=> fix: Update expected GeoJson results for both sicd chips

bin/process_image.py
- Move everything to main function as it will help to indicate whether the test failed or not in github workflow.  
=> fix: move to main func

src/aws/osml/utils/integ_utils.py
- Due to the recent change in this [PR](https://github.com/aws-solutions-library-samples/osml-model-runner/pull/47) (from `osml-model-runner`), when `batch_put_items` performed, it appends `-{random #}` as a `hash_key` and adds them to the DynamoDB table. If that were to happened and when the test is completed, it will query `image_id`, unforunately, `image_id` does not contains the appended `-{random #}`, thus the test will failed. 
**Test:**
> python3 bin/process_image.py --image large --model flood
```
INFO     root:integ_utils.py:384 Starting ModelRunner image job in us-west-2
INFO     root:integ_utils.py:385 Image: s3://test-images-328539665859/large.tif
INFO     root:integ_utils.py:386 Model: flood, Type:SM_ENDPOINT
INFO …
```
=> fix: DDB result returns empty if using batch_put_items

.github/copyright.yaml, .pre-commit-config.yaml, bin/get_cost_report.py, bin/process_image.py, bin/run_load_test.py, bin/translate_images.py, environment-py311.yml, environment.yml, src/aws/osml/integ/http_centerpoint/__init__.py, src/aws/osml/integ/http_centerpoint/test_http_centerpoint_model.py, src/aws/osml/integ/sm_aircraft/__init__.py, src/aws/osml/integ/sm_aircraft/test_sm_aircraft_model.py, src/aws/osml/integ/sm_centerpoint/__init__.py, src/aws/osml/integ/sm_centerpoint/test_sm_centerpoint_model.py, src/aws/osml/integ/sm_flood/__init__.py, src/aws/osml/integ/sm_flood/test_sm_flood_model.py, src/aws/osml/load/__init__.py, src/aws/osml/load/load_test.py, src/aws/osml/process_image/__init__.py, src/aws/osml/process_image/test_process_image.py, src/aws/osml/utils/__init__.py, src/aws/osml/utils/clients.py, src/aws/osml/utils/integ_utils.py, src/aws/osml/utils/osml_config.py, test/__init__.py, test/aws/osml/integ/test_import_integ.py
Updating copyright and adding pre-commit hooks to manage copyright going forward.
=> fix: update copyright

setup.cfg
=> build: update version to 2.0.0

setup.cfg
Updating config to release latest version update to upstream repos.
=> release: v2.0.0

.github/workflows/documentation-publish.yml, README.md, src/aws/osml/utils/integ_utils.py
- Meta integration test broken due to mismatched `sourceMetadata` dict. Certain values will always be unique.
- Update README since we do not have `.sh` script
=> hotfix: broken meta integration test

setup.cfg
- Update version number to 2.0.1
=> build: version update to v2.0.1

bin/process_image.py, src/aws/osml/utils/osml_config.py
Updating resource names to match CDK settings
=> fix: updating resource names

setup.cfg
- Version bump to `v2.0.2`
* fix: remove broken classification property from test data
* test: Implement ROI testing for aircraft model
* fix: updating resource names 
=> ci: version bump to v2.0.2

src/aws/osml/utils/integ_utils.py
- Revert this PR https://github.com/aws-solutions-library-samples/osml-model-runner-test/commit/e6412879f479d758f6f4467b553d88f3438f4e07 due to this PR https://github.com/aws-solutions-library-samples/osml-model-runner/pull/94
=> revert: 'validate kinesis extends to appends'

.github/workflows/build.yml, .github/workflows/docs.yml, .github/workflows/notify.yml, .github/workflows/pypi.yml, .github/workflows/release.yml, .github/workflows/tox.yml
- Add `workflow_dispatch` to all workflows
=> ci: add workflow_dispatch

setup.cfg
=> build: version bump to v2.0.3

setup.cfg
Bumping release version in ``setup.cfg`` to v2.1.0 for next release.
=> build: version bump to v2.1.0

setup.cfg
Updating the geojson version in this package is the previous is no longer supported in PyPi. This fixes broken installs of this package.
=> fix: updating geojson version
